[character_type.Creep]
ai = "Stupid"

[actor]
name = "ExampleNpc"
identifier = "examplenpc"
aseprite_path = "sprite_sheet.png"
pixel_size = [28.0, 28.0]

[actor.stats]
max_hp = 75
max_mana = 50
strength = 10
agility = 10
intelligence = 10
armor = 10
hp_regen = 2.5
mana_regen = 4.0
move_speed = 90.0
range = 48.0
arm_speed = 1.0

[actor.stats.damage]
physical = 5.0
elemental = "None"
