[package]
authors = ["Hellzbellz123 (Taylor Smith)"]
description = "Vanilla Coffee game: in progress"
documentation = "https://github.com/Hellzbellz123/VanillaCoffee/blob/main/README.md"
edition = "2021"
homepage = "https://github.com/Hellzbellz123/VanillaCoffee"
license-file = "LICENSE"
name = "vanillacoffee"
readme = "README.md"
repository = "https://github.com/Hellzbellz123/VanillaCoffee/"
version = "0.0.4"

[features]
trace = ["bevy/trace", "bevy/trace_tracy", "big-brain/trace", "dev"]
dev = ["bevy-debug-text-overlay/debug", "bevy_rapier2d/debug-render-2d"]
dev_linux = ["bevy/dynamic_linking", "dev"]

[workspace]
exclude = ["deps"]
resolver = "2"

[build-dependencies]
embed-resource = "2.1"

[target.x86_64-pc-windows-msvc.dependencies]
winapi = "0.3"

[dependencies]
rand = "0.8"
serde = "1.0"
strum = { version = "0.24", features = ["derive", "std", "strum_macros"] }
toml = "0.7"
tracing-error = "0.2"
tracing-log = "0.1"
winit = { version = "0.28", default-features = false, features = ["x11"] }
clap = "4.2"
tracing-subscriber = { version = "0.3" }
image = { version = "0.24", default_features = false, features = ["png"] }
voronator = "0.2"
petgraph = "0.6"
num-integer = "0.1"

# dot = "0.1.4"
# rayon = "1.7.0"

# rust_embed = {version = "6.4.2", features = ["debug-embed", "include-exclude"]}
# chrono = "0.4.23"
# serde_derive = "1.0.144"
# [dependencies.bevy_mod_transform2d]
# version = "0.3"
# features = ["bevy_rapier2d"]
# [dependencies.bevy_kindly]
# # git = https://github.com/Zeenobit/bevy_kindly
# version = "0.3.1"
# [dependencies.bevycheck]
# version = "0.5.2"
# [dependencies.grid_plane]
# path = "deps/grid_plane"
# [dependencies.bevy_debug_grid]
# path = "deps/bevy_debug_grid"
# [dependencies.pecs]
# path = "deps/pecs"

[dependencies.bevy]
path = "deps/bevy"
default-features = false
features = [
  "animation",          # Animation support
  "bevy_core_pipeline", # Higher-level rendering abstractions
  "bevy_gilrs",         # Gamepad input support
  "bevy_render",        # Rendering framework core
  "bevy_sprite",        # 2D (sprites) rendering
  "bevy_text",          # Text/font rendering
  "bevy_winit",         # Window management
  #"filesystem_watcher",   # Asset hot-reloading
  "serialize",            # Support for `serde` Serialize/Deserialize
  "subpixel_glyph_atlas", # Subpixel antialiasing for text/fonts
  "x11",                  # Linux: Support X11 windowing system
  # "wayland",              # LinuxL Support Wayland windowing system
  "bevy_ui", # UI toolkit
  #   "jpeg",
  "png",
]

[dependencies.bevy_graph]
path = "deps/bevy_graph"

[dependencies.bevy_console]
path = "deps/bevy-console"

[dependencies.bevy_asset_loader]
path = "deps/bevy_asset_loader/bevy_asset_loader"
features = ["2d", "standard_dynamic_assets"]

[dependencies.bevy_common_assets]
path = "deps/bevy_common_assets"
features = ["ron"]

[dependencies.bevy-debug-text-overlay]
path = "deps/bevy-debug-text-overlay"
default-features = false
features = ["builtin-font"]

[dependencies.bevy_ecs_tilemap]
path = "deps/bevy_ecs_tilemap"
features = ["atlas", "render"]

[dependencies.bevy_ecs_ldtk]
path = "deps/bevy_ecs_ldtk"
features = ["atlas"]

[dependencies.bevy_framepace]
path = "deps/bevy_framepace"

[dependencies.bevy-inspector-egui]
path = "deps/bevy-inspector-egui/crates/bevy-inspector-egui"

[dependencies.bevy_kira_audio]
path = "deps/bevy_kira_audio"
default-features = false
features = ["ogg"]

[dependencies.bevy_mod_debugdump]
path = "deps/bevy_mod_debugdump"
features = ["bevy_render", "render_graph"]

[dependencies.bevy_prototype_lyon]
path = "deps/bevy_prototype_lyon"

[dependencies.bevy_rapier2d]
path = "deps/bevy_rapier/bevy_rapier2d"
features = [
  # "parallel",
  "simd-nightly",
]

[dependencies.big-brain]
path = "deps/big-brain"

[dependencies.leafwing-input-manager]
path = "deps/leafwing-input-manager"

[dependencies.seldom_map_nav]
path = "deps/seldom_map_nav"

[patch.crates-io]
bevy = { path = "deps/bevy" }
bevy_a11y = { path = "deps/bevy/crates/bevy_a11y" }
bevy_animation = { path = "deps/bevy/crates/bevy_animation" }
bevy_app = { path = "deps/bevy/crates/bevy_app" }
bevy_asset = { path = "deps/bevy/crates/bevy_asset" }
bevy_core = { path = "deps/bevy/crates/bevy_core" }
bevy_core_pipeline = { path = "deps/bevy/crates/bevy_core_pipeline" }
bevy_derive = { path = "deps/bevy/crates/bevy_derive" }
bevy_diagnostic = { path = "deps/bevy/crates/bevy_diagnostic" }
bevy_ecs = { path = "deps/bevy/crates/bevy_ecs" }
bevy_encase_derive = { path = "deps/bevy/crates/bevy_encase_derive" }
bevy_gilrs = { path = "deps/bevy/crates/bevy_gilrs" }
bevy_gltf = { path = "deps/bevy/crates/bevy_gltf" }
bevy_hierarchy = { path = "deps/bevy/crates/bevy_hierarchy" }
bevy_input = { path = "deps/bevy/crates/bevy_input" }
bevy_internal = { path = "deps/bevy/crates/bevy_internal" }
bevy_log = { path = "deps/bevy/crates/bevy_log" }
bevy_macro_utils = { path = "deps/bevy/crates/bevy_macro_utils" }
bevy_math = { path = "deps/bevy/crates/bevy_math" }
bevy_mikktspace = { path = "deps/bevy/crates/bevy_mikktspace" }
bevy_pbr = { path = "deps/bevy/crates/bevy_pbr" }
bevy_ptr = { path = "deps/bevy/crates/bevy_ptr" }
bevy_reflect = { path = "deps/bevy/crates/bevy_reflect" }
bevy_render = { path = "deps/bevy/crates/bevy_render" }
bevy_scene = { path = "deps/bevy/crates/bevy_scene" }
bevy_sprite = { path = "deps/bevy/crates/bevy_sprite" }
bevy_tasks = { path = "deps/bevy/crates/bevy_tasks" }
bevy_text = { path = "deps/bevy/crates/bevy_text" }
bevy_time = { path = "deps/bevy/crates/bevy_time" }
bevy_ui = { path = "deps/bevy/crates/bevy_ui" }
bevy_utils = { path = "deps/bevy/crates/bevy_utils" }
bevy_window = { path = "deps/bevy/crates/bevy_window" }
bevy_dylib = { path = "deps/bevy/crates/bevy_dylib" }
bevy_dynamic_plugin = { path = "deps/bevy/crates/bevy_dynamic_plugin" }
bevy_audio = { path = "deps/bevy/crates/bevy_audio" }

[package.metadata.bundle]
copyright = "Copyright (c) Taylor Smith 2022. All rights reserved."
description = "Vanilla Coffee: a game in progress"
icon = ["assets/textures/stonercaticon.png"]
identifier = "io.github.hellzbellz123.vanillacoffee"
long_description = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
eiusmod tempor incididunt ut labore et dolore magna aliqua.  Ut
enim ad minim veniam, quis nostrud exercitation ullamco laboris
nisi ut aliquip ex ea commodo consequat.
"""
name = "Vanilla Coffee"
