
[package]
name = "vanillacoffee"
version = "0.0.3"
authors = ["Hellzbellz123 (Taylor Smith)"]
edition = "2021"
description = "Vanilla Coffee game: in progress"
documentation = "https://github.com/Hellzbellz123/VanillaCoffee/blob/main/README.md"
readme = "README.md"
homepage = "https://github.com/Hellzbellz123/VanillaCoffee"
repository = "https://github.com/Hellzbellz123/VanillaCoffee/"
license-file = "LICENSE"

[features]
dev_linux = ["bevy/dynamic", "dev"]
dev = ["bevy_rapier2d/debug-render"]

[workspace]
exclude = ["crates"]
resolver = "2"


[build-dependencies]
embed-resource = "1.7.3"

[dependencies]
rand = "0.8.5"
serde = "1.0.144"
serde_derive = "1.0.144"
winit = "0.27.5"

[dependencies.big-brain]
version = "0.15.0"
features = ["trace"]

# [dependencies.heron]
# version = "4.0.1"
# features = ["2d"]

[dependencies.bevy]
version = "0.9.0"
default-features = false
features = [
  "animation",          # Animation support
  "bevy_gilrs",         # Gamepad input support
  "bevy_winit",         # Window management
  "x11",                # Linux: Support X11 windowing system
  "filesystem_watcher", # Asset hot-reloading
  "bevy_render",        # Rendering framework core
  "bevy_core_pipeline", # Higher-level rendering abstractions
  "bevy_sprite",        # 2D (sprites) rendering
  "bevy_text",          # Text/font rendering
  # "bevy_ui",              # UI toolkit
  "png",
  "subpixel_glyph_atlas", # Subpixel antialiasing for text/fonts
  "serialize",            # Support for `serde` Serialize/Deserialize
  "jpeg",
]

[dependencies.bevy_ecs_ldtk]
# version = "0.4.0"
git = "https://github.com/Trouv/bevy_ecs_ldtk.git"
features = ["atlas"]

[dependencies.bevy_asset_loader]
version = "0.14.1"
# git = "https://github.com/NiklasEi/bevy_asset_loader.git"
features = ["2d"]

[dependencies.bevy_kira_audio]
version = "0.13.0"
default-features = false
features = ["ogg", "wav"]

[dependencies.bevy-inspector-egui]
version = "0.14.0"
default-features = false
features = ["bevy_render", "bevy_sprite", "bevy_text"]

[dependencies.bevy-inspector-egui-rapier]
version = "0.8.0"
features = ["rapier2d"]

[dependencies.bevy_rapier2d]
version = "0.19.0"
features = [
  "simd-nightly",
  "parallel",
  # "serde-serialize"
]


[dependencies.kayak_ui]
git = "https://github.com/StarArawn/kayak_ui.git"

[dependencies.leafwing-input-manager]
version = "0.7.0"
# path = "crates/leafwing-input-manager"
# git = "https://github.com/Leafwing-Studios/leafwing-input-manager"

[dependencies.image]
version = "0.24.3"
default-features = false
features = ["png"]

[target.x86_64-pc-windows-msvc.dependencies]
winapi = "0.3.9"

# [package.metadata.bundle]
# name = "Vanilla Coffee"
# identifier = "io.github.hellzbellz123.vanillacoffee"
# icon = ["assets/textures/stonercaticon.png"]
# copyright = "Copyright (c) Taylor Smith 2022. All rights reserved."
# description = "Vanilla Coffee game: in progress"
# long_description = """
# Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
# eiusmod tempor incididunt ut labore et dolore magna aliqua.  Ut
# enim ad minim veniam, quis nostrud exercitation ullamco laboris
# nisi ut aliquip ex ea commodo consequat.
# """
