[package]
authors = ["Hellzbellz123 (Taylor Smith)"]
description = "Vanilla Coffee game: in progress"
documentation = "https://github.com/Hellzbellz123/VanillaCoffee/blob/main/README.md"
edition = "2021"
homepage = "https://github.com/Hellzbellz123/VanillaCoffee"
license-file = "LICENSE"
name = "vanillacoffee"
readme = "README.md"
repository = "https://github.com/Hellzbellz123/VanillaCoffee/"
version = "0.0.4"

[features]
trace = ["bevy/trace", "bevy/trace_tracy", "big-brain/trace", "dev_linux"]
dev = ["bevy-debug-text-overlay/debug", "bevy_rapier2d/debug-render-2d"]
dev_linux = ["bevy/dynamic_linking", "dev"]

[[example]]
name = "test" # examples/boolean.rs

[workspace]
exclude = ["crates"]
resolver = "2"

[build-dependencies]
embed-resource = "2.1.1"

[target.x86_64-pc-windows-msvc.dependencies]
winapi = "0.3.9"

[dependencies]
rand = "0.8.5"
serde = "1.0.144"
strum = { version = "0.24.1", features = ["derive", "std", "strum_macros"] }
toml = "0.7.1"
tracing-error = "0.2.0"
tracing-log = "0.1.3"
winit = { version = "0.28.2", default-features = false, features = ["x11"] }
clap = "4.1.4"
tracing-subscriber = { version = "0.3.16" }
image = { version = "0.24.5", default_features = false, features = ["png"] }
grid_plane = "0.1.2"
# rust_embed = {version = "6.4.2", features = ["debug-embed", "include-exclude"]}
# chrono = "0.4.23"
# serde_derive = "1.0.144"

# [dependencies.bevy_mod_transform2d]
# version = "0.3"
# features = ["bevy_rapier2d"]

# [dependencies.bevy_kindly]
# # git = https://github.com/Zeenobit/bevy_kindly
# version = "0.3.1"

[dependencies.bevy_debug_grid]
path = "crates/bevy_debug_grid"

[dependencies.bevycheck]
version = "0.5.2"

[dependencies.bevy_console]
version = "0.7.0"
# path = "crates/bevy-console"
# git = "https://github.com/RichoDemus/bevy_console.git"

[dependencies.bevy]
version = "0.10.0"
default-features = false
features = [
  "animation",          # Animation support
  "bevy_core_pipeline", # Higher-level rendering abstractions
  "bevy_gilrs",         # Gamepad input support
  "bevy_render",        # Rendering framework core
  "bevy_sprite",        # 2D (sprites) rendering
  "bevy_text",          # Text/font rendering
  "bevy_winit",         # Window management
  #"filesystem_watcher",   # Asset hot-reloading
  "serialize",            # Support for `serde` Serialize/Deserialize
  "subpixel_glyph_atlas", # Subpixel antialiasing for text/fonts
  "x11",                  # Linux: Support X11 windowing system
  #"wayland",              # LinuxL Support Wayland windowing system
  "bevy_ui", # UI toolkit
  #   "jpeg",
  "png",
]

[dependencies.bevy_asset_loader]
version = "0.16.0"
# git = "https://github.com/NiklasEi/bevy_asset_loader.git"
features = ["2d", "standard_dynamic_assets"]

[dependencies.bevy_common_assets]
version = "0.6.0"
features = ["ron", "serde_ron", "serde_toml"]

[dependencies.bevy-debug-text-overlay]
version = "5.1.0"
default-features = false
features = ["builtin-font"]

[dependencies.bevy_ecs_tilemap]
version = "0.10.0"
features = ["atlas", "render"]

[dependencies.bevy_ecs_ldtk]
path = "crates/bevy_ecs_ldtk"
# git = "https://github.com/Hellzbellz123/bevy_ecs_ldtk.git"
# branch = "individual-levels-attempt"
features = ["atlas"]

[dependencies.bevy_framepace]
version = "0.12.1"

[dependencies.bevy-inspector-egui]
version = "0.18.3"

[dependencies.bevy_kira_audio]
version = "0.15.0"
default-features = false
features = ["ogg"]

[dependencies.bevy_mod_debugdump]
version = "0.7.0"
features = ["bevy_render", "render_graph"]

[dependencies.bevy_prototype_lyon]
version = "0.8.0"

[dependencies.bevy_rapier2d]
version = "0.21.0"
features = [
  # "parallel",
  "simd-nightly",
]

[dependencies.big-brain]
version = "0.17.0"
# git = "https://github.com/zkat/big-brain"
# path = "crates/big-brain"

[dependencies.leafwing-input-manager]
version = "0.9.1"
# git = "https://github.com/Leafwing-Studios/leafwing-input-manager"
# path = "crates/leafwing-0.24.5manager"

[package.metadata.bundle]
copyright = "Copyright (c) Taylor Smith 2022. All rights reserved."
description = "Vanilla Coffee: a game in progress"
icon = ["assets/textures/stonercaticon.png"]
identifier = "io.github.hellzbellz123.vanillacoffee"
long_description = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
eiusmod tempor incididunt ut labore et dolore magna aliqua.  Ut
enim ad minim veniam, quis nostrud exercitation ullamco laboris
nisi ut aliquip ex ea commodo consequat.
"""
name = "Vanilla Coffee"
