[package]
name = "aspen_halls_game"
version = "0.0.1"
edition = "2021"
authors = ["Hellzbellz123 (Taylor Smith)"]
description = "Aspen Halls: in progress"
documentation = "https://github.com/Hellzbellz123/AspenHalls/blob/main/README.md"
homepage = "https://hellzbellz123.github.io/AspenHalls/"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/Hellzbellz123/VanillaCoffee/"
keywords = ["videogame", "game", "application", "bin"]
categories = ["games"]



[workspace]
resolver = "2"
exclude = ["deps"]
members = ["launchers/wasm", "launchers/native", "launchers/mobile"]

[lib]
crate-type = ["cdylib", "rlib"]

[profile.dev]
opt-level = 1

[profile.release]
panic = 'abort'
codegen-units = 1
opt-level = 'z'
lto = true

[workspace.dependencies]
log = "0.4.20"
bevy = {path = "deps/bevy", default-features = false, features = [
    "android_shared_stdcxx",
    "bevy_asset",
    "bevy_pbr",
    "bevy_render",
    "bevy_scene",
    "bevy_text",
    "bevy_ui",
    "bevy_winit",
    "animation",             # Animation support
    "png",
    "serialize",             # Support for `serde` Serialize/Deserialize
    "subpixel_glyph_atlas",  # Subpixel antialiasing for text/fonts
    "wayland",               # LinuxL Support Wayland windowing system
    "bevy_gilrs",            # Gamepad input support
    "zstd",
    "bevy_sprite",           # 2D (sprites) rendering
    # "bevy_audio",
    # "x11",
    # "wav",
]}
# [dependencies.bevy]
# path = "deps/bevy"
# default-features = false
# features = [
#     "bevy_core_pipeline", # Higher-level rendering abstractions
#     "bevy_render",        # Rendering framework core
#     "bevy_text",          # Text/font rendering
#     "bevy_winit",         # Window management
#     #"filesystem_watcher",   # Asset hot-reloading
#     "x11",                  # Linux: Support X11 windowing system
#     "bevy_ui", # UI toolkit
#     #   "jpeg",
#     "png",
# ]

[features]
default = []
inspect = ["bevy-inspector-egui"]

[target.'cfg(not(target_family = "wasm"))'.features]
inspect = ["bevy/dynamic_linking", "bevy-inspector-egui"]

[build-dependencies]
embed-resource = "2.3.0"

[dependencies]
lazy_static = {version = "1.4.0"}
rand = {version = "0.8"}
log = {workspace = true}
serde = {version = "1.0"}
strum = {version = "0.25.0", features = ["derive", "std", "strum_macros"]}
toml = {version = "0.8.0"}
tracing-error = {version = "0.2"}
tracing-log = {version = "0.1"}
winit = {version = "0.28", default-features = false, features = ["x11"]}
clap = {version = "4.2"}
tracing-subscriber = {version = "0.3"}
image = {version = "0.24", default_features = false, features = ["png"]}
voronator = {version = "0.2"}
petgraph = {version = "0.6"}
num-integer = {version = "0.1"}
rust-embed = {version = "8.0.0", features = ["debug-embed", "include-exclude"]}
android_log-sys = {version = "0.3.1"}

# Bevy Dependencies are located in deps folder
big-brain = {path = "deps/big_brain"}
leafwing-input-manager = {path = "deps/leafwing_input_manager"}
seldom_map_nav = {path = "deps/seldom_map_nav", features = ["bevy"]}
belly = {path = "deps/belly"}
iyes_progress = {path = "deps/iyes_progress"}
bevy = {workspace = true}
bevy_sprite3d = {path = "deps/bevy_sprite3d"}
bevy_eventlistener = {path = "deps/bevy_eventlistener"}
bevy-inspector-egui = {path = "deps/bevy_inspector_egui/crates/bevy-inspector-egui", optional = true}
bevy_common_assets = {path = "deps/bevy_common_assets", features = ["ron"]}
bevy_ecs_ldtk = {path = "deps/bevy_ecs_ldtk", features = ["atlas"]}
bevy_ecs_tilemap = {path = "deps/bevy_ecs_tilemap", features = ["render"]}
bevy_framepace = {path = "deps/bevy_framepace"}
bevy_prototype_lyon = {path = "deps/bevy_prototype_lyon"}
bevy_mouse_tracking_plugin = { path = "deps/bevy_mouse_tracking"}
bevy_mod_picking = {path = "deps/bevy_mod_picking", default-features = false, features = [
    "all"
]}
bevy_tweening = {path = "deps/bevy_tweening", default-features = false, features = [
    "bevy_text",
]}
bevy_egui = {path = "deps/bevy_egui", default-features = false, features = [
    "default_fonts",
    "serde",
]}
bevy_asset_loader = {path = "deps/bevy_asset_loader/bevy_asset_loader", features = [
    "2d",
    "standard_dynamic_assets",
]}
bevy_kira_audio = {path = "deps/bevy_kira_audio", default-features = false, features = [
    "ogg",
]}
bevy_rapier2d = {path = "deps/bevy_rapier/bevy_rapier2d", features = [
    # "parallel",
    # "simd-nightly",
]}
bevy_mod_debugdump = {path = "deps/bevy_mod_debugdump", features = [
    "render_graph",
]}
bevy-debug-text-overlay = {path = "deps/bevy_debug_text_overlay", default-features = false, features = [
    "builtin-font",
]}
bevy_console = {path = "deps/bevy_console"}


[patch.crates-io]
# broken dependencies
navmesh ={ path = "deps/adepsdeps/navmesh"}
# bevy addon local replacements
bevy_ecs_tilemap = {path = "deps/bevy_ecs_tilemap"}
bevy_egui = {path = "deps/bevy_egui"}
bevy_common_assets = {path = "deps/bevy_common_assets"}
iyes_progress = {path = "deps/iyes_progress"}
bevy_ecs_ldtk_macros ={ path = "deps/bevy_ecs_ldtk/macros"}

# Replace bevy core crates with local copy for ALL crates that use them
bevy = {path = "deps/bevy"}
bevy_a11y = {path = "deps/bevy/crates/bevy_a11y"}
bevy_animation = {path = "deps/bevy/crates/bevy_animation"}
bevy_app = {path = "deps/bevy/crates/bevy_app"}
bevy_asset = {path = "deps/bevy/crates/bevy_asset"}
bevy_core = {path = "deps/bevy/crates/bevy_core"}
bevy_core_pipeline = {path = "deps/bevy/crates/bevy_core_pipeline"}
bevy_derive = {path = "deps/bevy/crates/bevy_derive"}
bevy_diagnostic = {path = "deps/bevy/crates/bevy_diagnostic"}
bevy_ecs = {path = "deps/bevy/crates/bevy_ecs"}
bevy_encase_derive = {path = "deps/bevy/crates/bevy_encase_derive"}
bevy_gilrs = {path = "deps/bevy/crates/bevy_gilrs"}
bevy_gltf = {path = "deps/bevy/crates/bevy_gltf"}
bevy_hierarchy = {path = "deps/bevy/crates/bevy_hierarchy"}
bevy_input = {path = "deps/bevy/crates/bevy_input"}
bevy_internal = {path = "deps/bevy/crates/bevy_internal"}
bevy_log = {path = "deps/bevy/crates/bevy_log"}
bevy_macro_utils = {path = "deps/bevy/crates/bevy_macro_utils"}
bevy_math = {path = "deps/bevy/crates/bevy_math"}
bevy_mikktspace = {path = "deps/bevy/crates/bevy_mikktspace"}
bevy_pbr = {path = "deps/bevy/crates/bevy_pbr"}
bevy_ptr = {path = "deps/bevy/crates/bevy_ptr"}
bevy_reflect = {path = "deps/bevy/crates/bevy_reflect"}
bevy_render = {path = "deps/bevy/crates/bevy_render"}
bevy_scene = {path = "deps/bevy/crates/bevy_scene"}
bevy_sprite = {path = "deps/bevy/crates/bevy_sprite"}
bevy_tasks = {path = "deps/bevy/crates/bevy_tasks"}
bevy_text = {path = "deps/bevy/crates/bevy_text"}
bevy_time = {path = "deps/bevy/crates/bevy_time"}
bevy_ui = {path = "deps/bevy/crates/bevy_ui"}
bevy_utils = {path = "deps/bevy/crates/bevy_utils"}
bevy_window = {path = "deps/bevy/crates/bevy_window"}
bevy_dylib = {path = "deps/bevy/crates/bevy_dylib"}
bevy_dynamic_plugin = {path = "deps/bevy/crates/bevy_dynamic_plugin"}
bevy_audio = {path = "deps/bevy/crates/bevy_audio"}
