[window_settings]
vsync = true
frame_rate_target = 60.0
fullscreen = false
resolution = [1280.0, 720.0]

[sound_settings]
mastervolume = 0.2
ambiencevolume = 0.2
musicvolume = 0.2
soundvolume = 0.2

[general_settings]
game_difficulty = "Medium"
camera_zoom = 1.0
