[window_settings]
vsync = true
frame_rate_target = 60.0
fullscreen = false
resolution = [1280.0, 720.0]

[sound_settings]
mastervolume = 0.6
ambiencevolume = 1.0
musicvolume = 0.2
soundvolume = 1.0

[general_settings]
camera_zoom = 1.0
