allow = [
    "clippy::multiple-crate-versions",
    "clippy::module_name_repetitions",
    "clippy::needless_pass_by_value",
    "clippy::struct-excessive-bools",
    "clippy::cast_possible_truncation",
    "clippy::cast_precision_loss",
    "clippy::cast-sign-loss",
    "clippy::cast_possible_wrap",
    "clippy::wildcard_imports",
    "clippy::unnecessary_struct_initialization",
]

deny = [
    "missing_docs",
    "clippy::correctness",
    "clippy::suspicious",
    "clippy::complexity",
    "clippy::perf",
    "clippy::style",
    "clippy::pedantic",
    "clippy::nursery",
    "clippy::cargo",
]

warn = [
    "clippy::too-many-lines",
    "clippy::missing_docs_in_private_items",
    "clippy::missing_errors_doc",
    "clippy::missing_panics_doc",
    "clippy::missing_safety_doc",
]

