[config]
skip_core_tasks = false
skip_git_env_info = false
skip_rust_env_info = false
skip_crate_env_info = false
load_cargo_aliases = false

[env]
CARGO_MAKE_WORKSPACE_EMULATION = true
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
CARGO_MAKE_CRATE_WORKSPACE_MEMBERS = [
  "crates/aspenlib",
  "crates/native",
  "crates/wasm",
  "crates/mobile",
]

[tasks.default]
alias = "pretty-list"

[tasks.pretty-list]
private = false
workspace = false
script.main = '''
  echo \
  "\
  CWD: $CARGO_MAKE_WORKING_DIRECTORY
  Below are predefined functions for the workspace:

    ##  Development  ##
      run-native: Run Aspen Halls for desktop.

    ##  Release ##
      create-release: builds all launchers in release mode and outputs artifacts too package dir

    ##  Utilities ##
      pretty-list: list all tasks that are worthwile in this workspace
  "
'''

[tasks.run-native]
dependencies = ["copy-assets"]
cwd = "crates/desktop/"
workspace = false
description = ""
command = "cargo"
args = ["run", "--features=develop,dynamic"]

[tasks.run-web]
dependencies = ["copy-assets"]
cwd = "crates/wasm/"
workspace = false
description = ""
command = "trunk"
args = ["serve", "--open", "--no-default-features", "--features", "develop"]

[tasks.run-mobile]
dependencies = ["copy-assets"]
cwd = "crates/mobile/"
workspace = false
description = ""
condition.env_set = ["BUNDLETOOL_PATH", "ANDROID_NDK_ROOT", "JAVA_HOME"]
command = "cargo"
args = ["apk", "run", "--package=aspen_halls_mobile", "--features=develop"]

[tasks.copy-assets]
workspace = false
script_runner = "@shell"
script.pre = "rm -rf crates/desktop/assets && cp -r assets crates/desktop/assets && rm -rf crates/wasm/assets && cp -r assets crates/wasm/assets && rm -rf crates/mobile/assets && cp -r assets crates/mobile/assets"

[tasks.package-release]
description = "runs package release workflow for each target"

# [tasks.connect-android]
# workspace = false
# description = "Connects first android device found by avahi-discover"
# script = "tools/adb-connecter.sh"
