[config]
skip_core_tasks = true
skip_git_env_info = true
skip_rust_env_info = true
skip_crate_env_info = true
default_to_workspace = true
min_version = "0.35.15"

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
CARGO_MAKE_WORKSPACE_EMULATION = true
CARGO_MAKE_CRATE_WORKSPACE_MEMBERS = ["launchers/native", "launchers/wasm", "launchers/mobile"]

[tasks.default]
alias = "list"

[tasks.edit_assets]
description = "Run Native app and save any changes too launchers/native/assets folder back too git tracked assets"

[tasks.run-native]
description = "Build and run desktop variant of game"

[tasks.run-mobile]
description = "Build and install on connected ADB device"

[tasks.run-web]
description = "Build game and open in web-browser"

[tasks.list]
description = "lists all tasks"
script = "cargo make --list-all-steps"

[tasks.docs]
description = "Generate docs"
command = "cargo"
args = ["doc", "--all"]

[tasks.upload-docs]
description = "Upload docs"
command = "cargo"
args = ["doc-upload"]

[tasks.clean]
description = "Clean all target directory"
command = "cargo"
args = ["clean"]

[tasks.fmt]
description = "Check format quality"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.fix-fmt]
description = "Fix format"
command = "cargo"
args = ["fmt", "--all"]

[tasks.clippy]
description = "Check code quality"
env_files = ["${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/.env"]
command = "cargo"
args = ["clippy", "--", "-D", "warnings"]

[tasks.fix-clippy]
description = "Fix code quality"
env_files = ["${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/.env"]
command = "cargo"
args = ["fix", "--allow-dirty"]

[tasks.test]
description = "Check all unit test"
env_files = ["${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/.env"]
command = "cargo"
args = ["test"]
dependencies = ["fmt", "clippy"]

[tasks.check]
description = "Check all issues, format and code quality"
dependencies = ["fmt", "clippy"]

[tasks.fix-all]
description = "Try fix all clippy and format issues"
dependencies = ["fix-fmt", "fix-clippy"]

[tasks.build-release]
description = "Generate release binary/lib"
dependencies = [
    "fmt",
    "clippy",
    "test",
    "release-native",
    "release-web",
]
