[tasks.run-native]
env_files = ["../../.env"]
script_runner = "@shell"
script.pre = "rm -rf ./assets && cp -r ../../assets ./assets"
script.main = "cargo run --features inspect"

[tasks.edit_assets]
env_files = ["../../.env"]
script_runner = "@shell"
script.pre = "rm -rf ../../assets_old/*"
script.main = "cargo run --features inspect"
script.post = "mv ../../assets/* ../../assets_old/ && cp -r ./assets/* ../../assets/"


[tasks.watch-native]
env_files = ["../../.env"]
script_runner = "@shell"
script.pre = "rm -fr ./assets && cp -r ../../assets ./assets"
script.main = "cargo run --features inspect"
watch.watch = [
    "../../src",
    "../../assets",
    "../../Cargo.toml",
    "assets",
    "src",
    "Cargo.toml",
]

[tasks.release-native]
env_files = ["../../.env"]
command = "cargo"
args = ["build", "--release"]
