[tasks.run-native]
env_files = ["../../.env"]
script_runner = "@shell"
script.pre = "rm -fr ./assets/* && cp -r ../../assets/* ./assets"
script.main = "cargo run --features inspect"

[tasks.watch-native]
env_files = ["../../.env"]
script_runner = "@shell"
script.pre = "rm -fr ./assets/* && cp -r ../../assets/* ./assets"
script.main = "cargo run --features inspect"
watch.watch = [
    "../../src",
    "../../assets",
    "../../Cargo.toml",
    "assets",
    "src",
    "Cargo.toml",
]

[tasks.release-native]
env_files = ["../../.env"]
command = "cargo"
args = ["build", "--release"]
