extend = "../../Makefile.toml"

[tasks.build-release]
private = true
workspace = false
run_task = { name = [
  "build-release-wasm",
  # "build-release-wasi"
] }

[tasks.cp_artifacts_release]
private = true
workspace = false
run_task = { name = [
  # assets are included inside the apk
  "cp_artifacts_wasm",
  # "cp_artifacts_wasi"
] }

[tasks.build-release-wasm]
env_files = ["../../.env"]
command = "trunk"
args = ["build", "--release"]

[tasks.cp_artifacts_wasm]
private = true
script_runner = "@shell"
script.main = "cp -r dist/* ../../package/website/"

[tasks.run-web]
env_files = ["../../.env"]
command = "trunk"
args = [
  "serve",
  "--open",
  "--no-default-features",
  "--features",
  "develop",
]
