[tasks.run-web]
env_files = ["../../.env"]
command = "trunk"
args = [
  "serve",
  "--open",
  "--no-default-features",
  "--features",
  "inspect",
]

[tasks.release-web]
env_files = ["../../.env"]
command = "trunk"
args = ["build", "--release"]
