[item_type.Weapon.damage]
physical = 150.0
elemental = "None"

[item_type.Weapon.form.Gun]
projectile_speed = 500.0
projectile_size = 5.0
barrel_end = [20.0, 0.0]
max_ammo = 7
reload_time = 2.0
fire_rate = 0.60

[actor]
name = "Small Pistol"
identifier = "smallpistol"
aseprite_path = "smallpistol.sprite.json"
pixel_size =  [10.0, 10.0]

[actor.stats]
max_hp = 10
max_mana = 20
armor = 2
hp_regen = 0.5
mana_regen = 0.5
move_speed = 10.0
strength = 2
agility = 2
intelligence = 6
damage = { physical = 2.0, elemental = "None" }
range = 48.0
arm_speed = 0.4