[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-Clink-arg=-fuse-ld=mold", "-Zshare-generics=y"]

[target.x86_64-pc-windows-msvc]
linker = "clang"
rustflags = [
  "-Lnative=/opt/xwin/crt/lib/x86_64",
  "-Lnative=/opt/xwin/sdk/lib/um/x86_64",
  "-Lnative=/opt/xwin/sdk/lib/ucrt/x86_64",
  "-Zshare-generics=n",
  "-Clink-arg=-fuse-ld=mold",
]

[profile.dev]  
opt-level = 1

[profile.dev.package."*"] # # Enable high optimizations for dependencies (incl. Bevy), but not for our code:
opt-level = 3

[profile.release]
lto = "thin"

[build]
# rustc-wrapper = "sccache"
# rustflags = ["-Ctarget-cpu=znver3"]


