[alias]
rld = "run --features=dev_linux --target=x86_64-unknown-linux-gnu"
rwd = "run --features=dev_linux --target=x86_64-pc-windows-msvc"

rwt = "build --target=x86_64-pc-windows-msvc -Zunstable-options --keep-going --out-dir=publish --release"
rlt = "build --target=x86_64-unknown-linux-gnu -Zunstable-options --keep-going --out-dir=publish --release"

[build]
target = ["x86_64-unknown-linux-gnu"]
rustc-wrapper = "/home/hellzbellz/.cargo/bin/sccache"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-Ctarget-cpu=native","-C", "link-arg=-fuse-ld=/usr/bin/mold", "-Zshare-generics=y"]


[profile.dev]
incremental = true
codegen-units = 256
opt-level = 1
debug = true

## Enable low optimizations for dependencies (incl. Bevy), also dont compile these incrementally so they can be cached
[profile.dev.package."*"] 
opt-level = 1
incremental = false
debug = true

[profile.release]
strip = "symbols"
debug = true 
codegen-units = 1
lto = "fat"
opt-level = 3
