[item_type.Weapon.damage]
physical = 30.0

[item_type.Weapon.damage.elemental]
Fire = 10.0

[item_type.Weapon.form.Gun]
projectile_speed = 50.0
projectile_size = 15.0
barrel_end = [20.0, 0.0]
max_ammo = 50
reload_time = 1.5
fire_rate = 0.25

[actor]
name = "ExampleWeapon"
identifier = "exampleweapon"
aseprite_path = "sprite_sheet.png"
pixel_size = [32.0, 32.0]

[actor.stats]
max_hp = 10
max_mana = 20
strength = 2
agility = 2
intelligence = 6
armor = 2
hp_regen = 0.5
mana_regen = 0.5
base_speed = 10.0
range = 48.0
arm_speed = 0.4000000059604645

[actor.stats.damage]
physical = 40.0
elemental = "None"
