#!/bin/bash

# Initialize a variable to store the extra arguments
extra_args=""

# Check if the "--no-casts" argument is present
if [[ "$*" == *"--no-casts"* ]]; then
    extra_args="${extra_args} -A clippy::cast_possible_truncation"
    extra_args="${extra_args} -A clippy::cast_precision_loss"
    extra_args="${extra_args} -A clippy::cast-sign-loss"
    extra_args="${extra_args} -A clippy::cast_possible_wrap"
fi

# Run cargo clippy with the specified arguments and extra_args
cargo clippy --features=inspect --no-deps -- \
    -D clippy::correctness \
    -D clippy::complexity \
    -D clippy::pedantic \
    -D clippy::nursery \
    -D clippy::perf \
    -D clippy::cargo \
    -A clippy::needless_pass_by_value \
    -A clippy::too-many-lines \
    -A clippy::struct-excessive-bools \
    -A clippy::multiple-crate-versions \
    $extra_args
